In [1]:
%pip install pandas

Requirement already satisfied: pandas in /usr/local/python/3.12.1/lib/python3.12/site-packages (3.0.3)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/python/3.12.1/lib/python3.12/site-packages (from pandas) (2.5.0)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/codespace/.local/lib/python3.12/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: six>=1.5 in /home/codespace/.local/lib/python3.12/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

[notice] A new release of pip is available: 26.0.1 -> 26.1.2
[notice] To update, run: pip install --upgrade pip
Note: you may need to restart the kernel to use updated packages.

In [2]:
import numpy as np
import pandas as pd

In [3]:
label=['a','b','c']
my_list=[10,20,30]
my_dict={1:10,2:20,3:30}
arr=np.array([10,20,30])

In [4]:
pd.Series(my_list)

0    10
1    20
2    30
dtype: int64

0 1 2 are labels and 10 20 30 are values

In [6]:
pd.Series(my_list,index=label)

a    10
b    20
c    30
dtype: int64

In [8]:
pd.Series(arr)

0    10
1    20
2    30
dtype: int64

In [9]:
pd.Series(arr,index=label)

a    10
b    20
c    30
dtype: int64

In [11]:
pd.Series(my_dict)

1    10
2    20
3    30
dtype: int64

DATAFRAMES

Dataframes are nothing but the combination of series

Creating a Dataframe

In [14]:
data = {
    'Name': ['John', 'Anna', 'Peter', 'Linda'],
    'Age': [28, 34, 29, 42],
    'City': ['New York', 'Paris', 'Berlin', 'London'],
    'Salary': [65000, 70000, 62000, 85000]
}
df=pd.DataFrame(data)

In [15]:
df

    Name  Age      City  Salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [64]:
data_list = [
    ['John', 28, 'New York', 65000],
    ['Anna', 34, 'Paris', 70000],
    ['Peter', 29, 'Berlin', 62000],
    ['Linda', 42, 'London', 85000]
]
df2=pd.DataFrame(data_list)
df2

       0   1         2      3
0   John  28  New York  65000
1   Anna  34     Paris  70000
2  Peter  29    Berlin  62000
3  Linda  42    London  85000

DF2 dataframe is created using list without having cloumn name/heading

In [65]:
columns=['name','age','city','salary']
df2=pd.DataFrame(data_list,columns=columns)

In [66]:
df2

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

In [67]:
df2['name']

0     John
1     Anna
2    Peter
3    Linda
Name: name, dtype: str

In [68]:
df2['city']

0    New York
1       Paris
2      Berlin
3      London
Name: city, dtype: str

In [69]:
df2[['name','city']]

    name      city
0   John  New York
1   Anna     Paris
2  Peter    Berlin
3  Linda    London

Creating a new columns

In [70]:
df2['designation']=['engineer','doctor','lawyer','engineer']
df2

    name  age      city  salary designation
0   John   28  New York   65000    engineer
1   Anna   34     Paris   70000      doctor
2  Peter   29    Berlin   62000      lawyer
3  Linda   42    London   85000    engineer

Removing a columns

In [71]:
df2.drop('designation',axis=1)

    name  age      city  salary
0   John   28  New York   65000
1   Anna   34     Paris   70000
2  Peter   29    Berlin   62000
3  Linda   42    London   85000

Axis=0 goes horizontal ,Axis=1 goes vertical for removing

In [72]:
df2

    name  age      city  salary designation
0   John   28  New York   65000    engineer
1   Anna   34     Paris   70000      doctor
2  Peter   29    Berlin   62000      lawyer
3  Linda   42    London   85000    engineer

inplace is nothing but removing the actual columns or data ,while drop delete the column virtually

In [73]:
df2

    name  age      city  salary designation
0   John   28  New York   65000    engineer
1   Anna   34     Paris   70000      doctor
2  Peter   29    Berlin   62000      lawyer
3  Linda   42    London   85000    engineer

In [82]:
df2.drop(0,axis=0)

    name  age    city  salary designation
1   Anna   34   Paris   70000      doctor
2  Peter   29  Berlin   62000      lawyer
3  Linda   42  London   85000    engineer

In [83]:
df2

    name  age      city  salary designation
0   John   28  New York   65000    engineer
1   Anna   34     Paris   70000      doctor
2  Peter   29    Berlin   62000      lawyer
3  Linda   42    London   85000    engineer

Selecting a row

In [85]:
df2.loc[0]

name               John
age                  28
city           New York
salary            65000
designation    engineer
Name: 0, dtype: object

In [90]:
df2.loc[[1,2]]

    name  age    city  salary designation
1   Anna   34   Paris   70000      doctor
2  Peter   29  Berlin   62000      lawyer

Selecting subsets of rows and columns

In [94]:
df2.loc[[0,1]][["city","salary"]]

       city  salary
0  New York   65000
1     Paris   70000

Conditional selection

In [95]:
df2

    name  age      city  salary designation
0   John   28  New York   65000    engineer
1   Anna   34     Paris   70000      doctor
2  Peter   29    Berlin   62000      lawyer
3  Linda   42    London   85000    engineer

In [96]:
# i only want to see the age is above thirty
df2[df2['age']>30]

    name  age    city  salary designation
1   Anna   34   Paris   70000      doctor
3  Linda   42  London   85000    engineer

In [99]:
# I only want the people whose age is greater than 30 and must be in paris
df2[(df2['age']>30) & (df2['designation']=='doctor')]

   name  age   city  salary designation
1  Anna   34  Paris   70000      doctor

MISSING DATA

In [100]:
data = {
    'A': [1, 2, np.nan, 4, 5],
    'B': [1, 2, 3, 4, 5],
    'C': [1, 2, 3, np.nan, np.nan],
    'D': [1, np.nan, np.nan, np.nan, 5]
}
df = pd.DataFrame(data)

In [101]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [102]:
df.isna()

       A      B      C      D
0  False  False  False  False
1  False  False  False   True
2   True  False  False   True
3  False  False   True   True
4  False  False   True  False

In [103]:
df.isna().sum()

A    1
B    0
C    2
D    3
dtype: int64

In [104]:
df.isna().sum().max()

np.int64(3)

If there is any missing value in each columns?

In [105]:
df.isna().any()

A     True
B    False
C     True
D     True
dtype: bool

In [106]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [107]:
df.dropna()

     A  B    C    D
0  1.0  1  1.0  1.0

In [108]:
df.dropna(thresh=3)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
4  5.0  5  NaN  5.0

Thresh is the minimum threshold value should be there in each row

In [109]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [110]:
df.fillna(0)

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  0.0
2  0.0  3  3.0  0.0
3  4.0  4  0.0  0.0
4  5.0  5  0.0  5.0

In [112]:
values={'A':0,'B':100,'C':200,'D':300}
df.fillna(value=values)

     A  B      C      D
0  1.0  1    1.0    1.0
1  2.0  2    2.0  300.0
2  0.0  3    3.0  300.0
3  4.0  4  200.0  300.0
4  5.0  5  200.0    5.0

In [113]:
df

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  NaN
2  NaN  3  3.0  NaN
3  4.0  4  NaN  NaN
4  5.0  5  NaN  5.0

In [114]:
df.fillna(df.mean())

     A  B    C    D
0  1.0  1  1.0  1.0
1  2.0  2  2.0  3.0
2  3.0  3  3.0  3.0
3  4.0  4  2.0  3.0
4  5.0  5  2.0  5.0

Merging joining concatination

In [115]:
employees = pd.DataFrame({
    'employee_id': [1, 2, 3, 4, 5],
    'name': ['John', 'Anna', 'Peter', 'Linda', 'Bob'],
    'department': ['HR', 'IT', 'Finance', 'IT', 'HR']
})

# DataFrame 2: Salary information
salaries = pd.DataFrame({
    'employee_id': [1, 2, 3, 6, 7],
    'salary': [60000, 80000, 65000, 70000, 90000],
    'bonus': [5000, 10000, 7000, 8000, 12000]
})

In [116]:
employees

   employee_id   name department
0            1   John         HR
1            2   Anna         IT
2            3  Peter    Finance
3            4  Linda         IT
4            5    Bob         HR

In [117]:
salaries

   employee_id  salary  bonus
0            1   60000   5000
1            2   80000  10000
2            3   65000   7000
3            6   70000   8000
4            7   90000  12000

In [ ]:
pd.merge(employees,salaries,on='employee_id')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

In [120]:
pd.merge(employees,salaries,on='employee_id',how='inner')

   employee_id   name department  salary  bonus
0            1   John         HR   60000   5000
1            2   Anna         IT   80000  10000
2            3  Peter    Finance   65000   7000

kind of inner,outer,left,right joins


Concatination of 2 dataframe

In [122]:

df1 = pd.DataFrame({
    'A': ['A0', 'A1', 'A2'],
    'B': ['B0', 'B1', 'B2'],
    'C': ['C0', 'C1', 'C2']
})

df2 = pd.DataFrame({
    'A': ['A3', 'A4', 'A5'],
    'B': ['B3', 'B4', 'B5'],
    'C': ['C3', 'C4', 'C5']
})

In [124]:
df1

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2

In [125]:
df2

    A   B   C
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [126]:
pd.concat([df1,df2])

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

In [127]:
pd.concat([df1,df2],axis=0)

    A   B   C
0  A0  B0  C0
1  A1  B1  C1
2  A2  B2  C2
0  A3  B3  C3
1  A4  B4  C4
2  A5  B5  C5

joingin 2 dataframes

In [128]:

df1 = pd.DataFrame({
    'name': ['Alice', 'Bob', 'Charlie']
}, index=[1, 2, 3])

# Second DataFrame
df2 = pd.DataFrame({
    'score': [85, 90, 75]
}, index=[2, 3, 4])

In [129]:
df1

      name
1    Alice
2      Bob
3  Charlie

In [130]:
df2

   score
2     85
3     90
4     75

In [131]:

df1.join(df2,how='outer')

      name  score
1    Alice    NaN
2      Bob   85.0
3  Charlie   90.0
4      NaN   75.0

In [132]:

df2.join(df1)

   score     name
2     85      Bob
3     90  Charlie
4     75      NaN

Aggregation

In [133]:

data = {
    'Category': ['A', 'B', 'A', 'B', 'A', 'B', 'A', 'B'],
    'Store': ['S1', 'S1', 'S2', 'S2', 'S1', 'S2', 'S2', 'S1'],
    'Sales': [100, 200, 150, 250, 120, 180, 200, 300],
    'Quantity': [10, 15, 12, 18, 8, 20, 15, 25],
    'Date': pd.date_range('2023-01-01', periods=8)
}
df = pd.DataFrame(data)

In [134]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [137]:
# Group by Category and calculate the sum of Sales
cat=df.groupby('Category')['Sales'].sum()
cat

Category
A    570
B    930
Name: Sales, dtype: int64

In [138]:

# Group by Store and calculate the sum of Sales
cat = df.groupby('Store')['Sales'].sum()
cat

Store
S1    720
S2    780
Name: Sales, dtype: int64

In [139]:
# Group by multiple columns
# Group by Category and Store
cat = df.groupby(['Category','Store'])['Sales'].sum()
cat

Category  Store
A         S1       220
          S2       350
B         S1       500
          S2       430
Name: Sales, dtype: int64

Aggregation

In [140]:

df['Sales'].mean()
"""mean median min max count std """

'mean median min max count std '

In [141]:
df

  Category Store  Sales  Quantity       Date
0        A    S1    100        10 2023-01-01
1        B    S1    200        15 2023-01-02
2        A    S2    150        12 2023-01-03
3        B    S2    250        18 2023-01-04
4        A    S1    120         8 2023-01-05
5        B    S2    180        20 2023-01-06
6        A    S2    200        15 2023-01-07
7        B    S1    300        25 2023-01-08

In [142]:

df['Sales'].agg(['sum', 'mean', 'min', 'max', 'count', 'std', 'median'])

sum       1500.000000
mean       187.500000
min        100.000000
max        300.000000
count        8.000000
std         66.062741
median     190.000000
Name: Sales, dtype: float64